variables:
  GIT_DEPTH: 0

stages:
  - dependences
  - build
  - publish

dependences_dev:
  stage: dependences
  tags:
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH =~ /dev/
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
  script:
    - npm install

build_dev:
  stage: build
  tags:
    - dev
  rules:
    - if: $CI_COMMIT_BRANCH =~ /dev/
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - ng build --configuration dev

publish_dev:
  variables:
    DEPLOY: "/var/www/dev"
    FOLDER: "promette"
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH =~ /dev/
  tags:
    - dev
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - echo "Desplegando a dev"
    - TAG_VERSION=$(git describe --tags --long | sed 's/-g[0-9a-f]\+$//')
    - mkdir -p $DEPLOY/$FOLDER/
    - rm -rf $DEPLOY/$FOLDER/*
    - mkdir -p $DEPLOY/$FOLDER/version
    - cp -r $CI_PROJECT_DIR/dist/browser/. $DEPLOY/$FOLDER/
    - |
      echo "{
        \"version\": \"$TAG_VERSION\"
      }" > $DEPLOY/$FOLDER/version/version.json

dependences_uat:
  stage: dependences
  tags:
    - uat
  rules:
    - if: $CI_COMMIT_BRANCH =~ /uat/
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
  script:
    - npm install

build_uat:
  stage: build
  tags:
    - uat
  rules:
    - if: $CI_COMMIT_BRANCH =~ /uat/
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - ng build --configuration uat

publish_uat:
  variables:
    DEPLOY: "/var/www/uat"
    FOLDER: "promette"
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH =~ /uat/
  tags:
    - uat
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - echo "Desplegando a UAT..."
    - TAG_VERSION=$(git describe --tags --long | sed 's/-g[0-9a-f]\+$//')
    - mkdir -p $DEPLOY/$FOLDER/
    - rm -rf $DEPLOY/$FOLDER/*
    - mkdir -p $DEPLOY/$FOLDER/version
    - cp -r $CI_PROJECT_DIR/dist/browser/. $DEPLOY/$FOLDER/
    - |
      echo "{
        \"version\": \"$TAG_VERSION\"
      }" > $DEPLOY/$FOLDER/version/version.json

dependences_prod:
  stage: dependences
  tags:
    - prod-promette
  rules:
    - if: $CI_COMMIT_BRANCH =~ /main/
  cache:
    key:
      files:
        - package.json
    paths:
      - node_modules
  script:
    - npm install

build_prod:
  stage: build
  tags:
    - prod-promette
  rules:
    - if: $CI_COMMIT_BRANCH =~ /main/
  cache:
    - key:
        files:
          - package.json
      paths:
        - node_modules
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - ng build

publish_prod:
  variables:
    DEPLOY: "/var/www"
    FOLDER: "promette"
  stage: publish
  rules:
    - if: $CI_COMMIT_BRANCH =~ /main/
  tags:
    - prod-promette
  cache:
    - key: cache-$CI_COMMIT_REF_SLUG
      paths:
        - dist
  script:
    - echo "Desplegando a prod"
    - TAG_VERSION=$(git describe --tags --long | sed 's/-g[0-9a-f]\+$//')
    - mkdir -p $DEPLOY/$FOLDER/
    - rm -rf $DEPLOY/$FOLDER/*
    - mkdir -p $DEPLOY/$FOLDER/version
    - cp -r $CI_PROJECT_DIR/dist/browser/. $DEPLOY/$FOLDER/
    - |
      echo "{
        \"version\": \"$TAG_VERSION\"
      }" > $DEPLOY/$FOLDER/version/version.json
